/**
 * Capacity intelligence + resource model.
 *
 * Provides a transparent, illustrative model of the service-management effort
 * generated by incidents, and how much of it supervised automation can absorb.
 *
 * IMPORTANT: every figure here is an ILLUSTRATIVE model built on stated
 * assumptions and synthetic data. Relay does not present these as guaranteed
 * savings. See docs/orchestration-methodology.md.
 */

export interface ResourceScenarioInput {
  incidentCount: number;
  /** Average minutes to handle one incident fully manually. */
  manualHandlingMins: number;
  /** Share of incidents eligible for supervised automation (0-100). */
  automatedHandlingPct: number;
  /** Human review minutes per automated incident (approval + verification). */
  humanReviewMins: number;
  /** Share of incidents that escalate regardless (0-100). */
  escalationPct: number;
  /** Total support staff capacity in hours for the period. */
  supportStaffCapacityHours: number;
}

export interface ResourceModelResult {
  estimatedManualWorkloadHours: number;
  estimatedAutomatedWorkloadHours: number;
  totalWorkloadHours: number;
  baselineFullyManualHours: number;
  potentialHoursAvoided: number;
  capacityUtilisationPct: number;
  automatedIncidentCount: number;
  manualIncidentCount: number;
  assumptions: string[];
}

const round1 = (n: number) => Math.round(n * 10) / 10;

/**
 * Compute the illustrative resource model for a scenario.
 *
 * Model:
 *   - baseline = every incident handled fully manually
 *   - automated incidents still cost `humanReviewMins` (human-in-the-loop)
 *   - escalated incidents always cost full manual handling
 */
export function computeResourceModel(input: ResourceScenarioInput): ResourceModelResult {
  const {
    incidentCount,
    manualHandlingMins,
    automatedHandlingPct,
    humanReviewMins,
    escalationPct,
    supportStaffCapacityHours,
  } = input;

  const escalated = Math.round(incidentCount * (escalationPct / 100));
  const automatable = Math.round(
    (incidentCount - escalated) * (automatedHandlingPct / 100),
  );
  const manual = incidentCount - automatable;

  const manualWorkloadHours = (manual * manualHandlingMins) / 60;
  const automatedWorkloadHours = (automatable * humanReviewMins) / 60;
  const totalWorkloadHours = manualWorkloadHours + automatedWorkloadHours;

  const baselineFullyManualHours = (incidentCount * manualHandlingMins) / 60;
  const potentialHoursAvoided = baselineFullyManualHours - totalWorkloadHours;

  const capacityUtilisationPct =
    supportStaffCapacityHours > 0
      ? (totalWorkloadHours / supportStaffCapacityHours) * 100
      : 0;

  return {
    estimatedManualWorkloadHours: round1(manualWorkloadHours),
    estimatedAutomatedWorkloadHours: round1(automatedWorkloadHours),
    totalWorkloadHours: round1(totalWorkloadHours),
    baselineFullyManualHours: round1(baselineFullyManualHours),
    potentialHoursAvoided: round1(potentialHoursAvoided),
    capacityUtilisationPct: round1(capacityUtilisationPct),
    automatedIncidentCount: automatable,
    manualIncidentCount: manual,
    assumptions: [
      `Average manual handling time: ${manualHandlingMins} min/incident.`,
      `${automatedHandlingPct}% of non-escalated incidents eligible for supervised automation.`,
      `Automated incidents still require ${humanReviewMins} min of human review.`,
      `${escalationPct}% of incidents escalate to full manual handling regardless.`,
      "Figures are illustrative, based on synthetic data — not guaranteed savings.",
    ],
  };
}

// --- Aggregate metrics used by the Command Centre & Capacity views ----------

export interface MttPair {
  mttaMinutes: number | null;
  mttrMinutes: number | null;
}

/** Mean time to acknowledge / resolve from incident timestamps. */
export function computeMtt(
  incidents: {
    detectedAt: Date;
    acknowledgedAt: Date | null;
    resolvedAt: Date | null;
  }[],
): MttPair {
  const ackDeltas: number[] = [];
  const resolveDeltas: number[] = [];
  for (const inc of incidents) {
    if (inc.acknowledgedAt) {
      ackDeltas.push((inc.acknowledgedAt.getTime() - inc.detectedAt.getTime()) / 60000);
    }
    if (inc.resolvedAt) {
      resolveDeltas.push((inc.resolvedAt.getTime() - inc.detectedAt.getTime()) / 60000);
    }
  }
  return {
    mttaMinutes: ackDeltas.length ? round1(avg(ackDeltas)) : null,
    mttrMinutes: resolveDeltas.length ? round1(avg(resolveDeltas)) : null,
  };
}

export function automationRate(automated: number, total: number): number {
  if (total <= 0) return 0;
  return round1((automated / total) * 100);
}

function avg(values: number[]): number {
  return values.reduce((a, b) => a + b, 0) / values.length;
}
